services:
  app:
    build: .
    container_name: Universal_Bot
    restart: unless-stopped
    volumes:
      - ./db:/app/db
      - ./plugins:/app/bot/custom_plugins
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
